version: '3.7'

services:
    mongodb_example:
        image: mongo:latest
        container_name: mongodb_example
        restart: always
        environment:
            MONGO_INITDB_ROOT_USERNAME: mongo_user
            MONGO_INITDB_ROOT_PASSWORD: mongo_password
            MONGO_INITDB_DATABASE: example_db
        ports:
            - 27018:27017
        volumes:
            - ./mongo-init.js:/docker-entrypoint-initdb.d/mongo-init.js:ro